apiVersion: v1
kind: Service
metadata:
  name: task-api-service
spec:
  # Expose the application on a specific port accessible from outside the cluster
  type: NodePort 
  selector:
    app: task-api # Must match the 'labels' in your deployment.yaml
  ports:
    - protocol: TCP
    - port: 8081      # The port the service itself listens on
      targetPort: 8081 # The port the container exposes (from Dockerfile)
      nodePort: 30080 # The host port to access the service (e.g., http://localhost:30080)