name: CI Build and Docker Push

on:
  push:
    branches:
      - main  # Workflow triggers when code is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      [cite_start]uses: actions/checkout@v3 [cite: 256]

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        [cite_start]java-version: '17' [cite: 256]
        [cite_start]distribution: 'temurin' [cite: 256]
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        [cite_start]path: ~/.m2 [cite: 257]
        [cite_start]key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }} [cite: 257]
        restore-keys: |
          ${{ runner.os }}-m2- [cite: 258]

    # Code Build Step
    - name: Build with Maven
      # The -B flag is for batch mode, and -DskipTests skips running tests
      [cite_start]run: mvn -B package --file pom.xml -DskipTests [cite: 258]

    # Docker Build and Push Steps
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        [cite_start]username: ${{ secrets.DOCKERHUB_USERNAME }} [cite: 258]
        [cite_start]password: ${{ secrets.DOCKERHUB_TOKEN }} [cite: 258]

    - name: Build and push Docker image
      [cite_start]uses: docker/build-push-action@v4 [cite: 259]
      with:
        [cite_start]context: . [cite: 260]
        [cite_start]push: true [cite: 260]
        # Replace 'your-dockerhub-username' with your actual username
        [cite_start]tags: ${{ secrets.DOCKERHUB_USERNAME }}/kaiburr-task-app:latest [cite: 260]