name: CI Build and Docker Push

on:
  push:
    branches:
      - main  # Workflow triggers when code is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-

    # Code Build Step (Already Fixed)
    - name: Build with Maven
      # We changed this to point to the subdirectory
      run: mvn -B package --file task-api/pom.xml -DskipTests

    # Docker Build and Push Steps
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        # FIX: Changed the context to point to the subdirectory containing the Dockerfile
        context: task-api 
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/kaiburr-task-app:latest